### ISSUE TITLE
problem with my project

### ISSUE THREAD

**Issue by zroty** [ItsMeSudo/Average-Tiktok-Programmer#1]
its not working on my pc

its my problem: -bash: go: command not found

what ken i du?

**Comment by ItsMeSudo** [comment]
Here’s a step-by-step guide for each operating system to help you get started with Go.

### For Windows Users:

1. **Download the Installer:**
   - Visit the Go official download page: [https://go.dev/dl/](https://go.dev/dl/)
   - Choose the Windows installer file (usually named something like `gox.xx.x.windows-amd64.msi` where `x.xx.x` represents the version number).
   - Download the `.msi` file.

2. **Install Go:**
   - Once the download is complete, double-click the `.msi` file to start the installer.
   - Follow the installation prompts. It’s recommended to leave the default installation options unless you have a specific reason to change them.
   - Ensure that the checkbox for “Add Go to the PATH” is selected. This makes the Go executable accessible from your command prompt.

3. **Verify Installation:**
   - Open your Command Prompt (you can search for `cmd` in the Start menu).
   - Type `go version` and press Enter. If Go is installed correctly, it should display the installed version.

### For macOS Users:

1. **Download the Installer:**
   - Visit the Go official download page: [https://go.dev/dl/](https://go.dev/dl/)
   - Select the macOS package (typically named `gox.xx.x.darwin-amd64.pkg`).
   - Download the package file.

2. **Install Go:**
   - Open the downloaded `.pkg` file by double-clicking it.
   - This will open an installer; follow the instructions to install Go. Like Windows, it’s best to stick with the default installation settings.

3. **Verify Installation:**
   - Open the Terminal (you can find it using Spotlight with `Cmd + Space` and typing "Terminal").
   - Type `go version` and press Enter. If Go is installed correctly, you should see the version of Go displayed.

### For Linux Users:

1. **Download the Tarball:**
   - Visit the Go official download page: [https://go.dev/dl/](https://go.dev/dl/)
   - Choose the appropriate version for your architecture (for example, `gox.xx.x.linux-amd64.tar.gz`).
   - Download the tarball file.

2. **Extract and Install Go:**
   - Open a terminal.
   - Extract the tarball to `/usr/local` using the following command:
     ```
     sudo tar -C /usr/local -xzf gox.xx.x.linux-amd64.tar.gz
     ```
   - Replace `gox.xx.x.linux-amd64.tar.gz` with the actual filename.

3. **Set Up the Environment Variables:**
   - Open your profile for editing (for example, `~/.bash_profile`, `~/.bashrc`, or `~/.profile`) using a text editor like nano:
     ```
     nano ~/.profile
     ```
   - Add the following lines at the end of the file:
     ```
     export PATH=$PATH:/usr/local/go/bin
     export GOPATH=$HOME/go
     export PATH=$PATH:$GOPATH/bin
     ```
   - Save and close the editor. Then, update your profile:
     ```
     source ~/.profile
     ```

4. **Verify Installation:**
   - In your terminal, type `go version` and press Enter. You should see the installed version of Go.

By following these steps, you can successfully install Go on your PC, regardless of your operating system. Once installed, you can start building your Go projects! If you encounter any issues, the [Go documentation](https://go.dev/doc/) is a great resource for troubleshooting and learning more about the Go language.

**Comment by zroty** [comment]
i dont know how can i install this that thut?

can u help on telegram? https://t.me/CryptoMoonShots_Chat
